import type { Announcement, Category, Product } from "./types";

/**
 * Demo content used when Supabase environment variables are not configured yet,
 * so the site is fully browsable before the database is connected.
 */
export const seedCategories: Category[] = [
  { id: "cat-panels", name: "Solar Panels", slug: "solar-panels" },
  { id: "cat-inverters", name: "Inverters", slug: "inverters" },
  { id: "cat-batteries", name: "Batteries", slug: "batteries" },
  { id: "cat-systems", name: "Complete Systems", slug: "complete-systems" },
  { id: "cat-accessories", name: "Accessories", slug: "accessories" },
  { id: "cat-water-heating", name: "Water Heating", slug: "water-heating" },
];

const baseDate = "2025-01-15T10:00:00.000Z";

export const seedProducts: Product[] = [
  {
    id: "prd-1",
    slug: "monocrystalline-solar-panel-580w",
    name: "SunPower Mono 580W Panel",
    title: "High-efficiency monocrystalline module for rooftop and commercial arrays",
    description:
      "Our flagship 580W monocrystalline module delivers dependable output even in high ambient temperatures. Half-cut cell architecture reduces resistive loss and keeps the panel producing when part of the array is shaded, while the anodised aluminium frame is tested for heavy wind and snow loads.\n\nEvery module is individually flash-tested before dispatch and shipped with a 25-year linear performance warranty, making it a safe long-term investment for homes, factories and agricultural sites.",
    price: 34500,
    discount_price: 29900,
    category_id: "cat-panels",
    images: ["/images/product-solar-panel.jpg", "/images/product-rooftop-system.jpg"],
    videos: [],
    documents: [{ name: "Datasheet (PDF)", url: "/docs/sample-datasheet.pdf" }],
    features: [
      "580W peak output with 22.4% module efficiency",
      "Half-cut mono PERC cells for better shade tolerance",
      "Anti-reflective, self-cleaning tempered glass",
      "Corrosion-resistant anodised aluminium frame",
      "25-year linear performance warranty",
    ],
    specifications: [
      { label: "Peak power", value: "580 W" },
      { label: "Module efficiency", value: "22.4%" },
      { label: "Cell type", value: "Monocrystalline PERC, half-cut" },
      { label: "Dimensions", value: "2278 × 1134 × 35 mm" },
      { label: "Weight", value: "27.5 kg" },
      { label: "Operating temperature", value: "-40°C to +85°C" },
      { label: "Warranty", value: "12 years product / 25 years performance" },
    ],
    is_active: true,
    is_featured: true,
    created_at: baseDate,
  },
  {
    id: "prd-2",
    slug: "hybrid-inverter-8kw",
    name: "PowerCore Hybrid Inverter 8kW",
    title: "Grid-tied hybrid inverter with battery backup and app monitoring",
    description:
      "The PowerCore 8kW hybrid inverter runs your home on solar during the day, charges the battery with surplus energy and switches to backup in under 10 milliseconds when the grid drops. Dual MPPT trackers let you split panels across two roof faces without losing yield.\n\nA colour display and mobile app give you live production, consumption and battery data, so you always know exactly where your energy is going.",
    price: 415000,
    discount_price: null,
    category_id: "cat-inverters",
    images: ["/images/product-inverter.jpg"],
    videos: [],
    documents: [{ name: "Installation Manual (PDF)", url: "/docs/sample-datasheet.pdf" }],
    features: [
      "8kW continuous output, 16kW surge for motor loads",
      "Dual MPPT trackers with wide voltage window",
      "Under 10 ms transfer to backup power",
      "Wi-Fi monitoring through mobile app",
      "Works with lithium and lead-acid batteries",
    ],
    specifications: [
      { label: "Rated power", value: "8000 W" },
      { label: "Max PV input", value: "12000 W" },
      { label: "MPPT trackers", value: "2" },
      { label: "Battery voltage", value: "48 V" },
      { label: "Peak efficiency", value: "97.6%" },
      { label: "Protection rating", value: "IP65" },
      { label: "Warranty", value: "5 years" },
    ],
    is_active: true,
    is_featured: true,
    created_at: baseDate,
  },
  {
    id: "prd-3",
    slug: "lithium-battery-10kwh",
    name: "EnduraStore 10kWh Lithium Battery",
    title: "Wall-mounted LiFePO4 storage for reliable overnight backup",
    description:
      "EnduraStore stores the solar energy you generate during the day so your home keeps running through load shedding and after sunset. The LiFePO4 chemistry is rated for 6,000+ cycles, which means a decade of daily use without meaningful capacity loss.\n\nAn integrated battery management system continuously balances cells and protects against over-charge, over-discharge and thermal events.",
    price: 620000,
    discount_price: 575000,
    category_id: "cat-batteries",
    images: ["/images/product-battery.jpg"],
    videos: [],
    documents: [],
    features: [
      "10 kWh usable capacity, stackable to 40 kWh",
      "LiFePO4 cells rated for 6,000+ cycles",
      "Built-in smart battery management system",
      "Slim wall-mounted design with LED status",
      "10-year warranty",
    ],
    specifications: [
      { label: "Usable capacity", value: "10 kWh" },
      { label: "Nominal voltage", value: "51.2 V" },
      { label: "Chemistry", value: "LiFePO4" },
      { label: "Cycle life", value: "6000+ cycles at 80% DoD" },
      { label: "Dimensions", value: "700 × 550 × 190 mm" },
      { label: "Weight", value: "96 kg" },
      { label: "Warranty", value: "10 years" },
    ],
    is_active: true,
    is_featured: true,
    created_at: baseDate,
  },
  {
    id: "prd-4",
    slug: "complete-home-system-10kw",
    name: "Complete Home Solar System 10kW",
    title: "Turnkey rooftop package including panels, inverter, mounting and installation",
    description:
      "A fully engineered 10kW package for medium to large homes, covering everything from site survey and structural mounting to net-metering paperwork. We size the array around your actual consumption so you are not paying for capacity you will never use.\n\nInstallation is completed by our own certified crews, and the system is handed over with commissioning reports and a full performance walkthrough.",
    price: 2450000,
    discount_price: 2295000,
    category_id: "cat-systems",
    images: ["/images/product-rooftop-system.jpg", "/images/product-solar-panel.jpg"],
    videos: [],
    documents: [{ name: "System Brochure (PDF)", url: "/docs/sample-datasheet.pdf" }],
    features: [
      "18 × 580W monocrystalline panels",
      "10kW hybrid inverter with monitoring",
      "Galvanised mounting structure and DC protection",
      "Complete installation and commissioning",
      "Net-metering documentation support",
    ],
    specifications: [
      { label: "System size", value: "10 kW" },
      { label: "Estimated output", value: "1,300 – 1,450 units per month" },
      { label: "Roof area required", value: "Approx. 600 sq ft" },
      { label: "Installation time", value: "3 – 5 working days" },
      { label: "Warranty", value: "System warranty up to 25 years" },
    ],
    is_active: true,
    is_featured: true,
    created_at: baseDate,
  },
  {
    id: "prd-5",
    slug: "solar-water-pump-system",
    name: "AgriFlow Solar Water Pump",
    title: "Diesel-free irrigation powered entirely by sunlight",
    description:
      "AgriFlow replaces diesel pumping with a solar-driven submersible system built for daily agricultural use. The VFD controller adjusts pump speed with available sunlight, delivering steady flow from early morning to late afternoon.\n\nWith no fuel bills and almost no maintenance, most growers recover the cost of the system within a few seasons.",
    price: 385000,
    discount_price: null,
    category_id: "cat-systems",
    images: ["/images/product-solar-pump.jpg"],
    videos: [],
    documents: [],
    features: [
      "Runs without diesel, grid power or batteries",
      "Variable frequency drive matches pump speed to sunlight",
      "Stainless steel submersible pump body",
      "Dry-run and over-voltage protection",
      "Suitable for 1 – 5 HP irrigation needs",
    ],
    specifications: [
      { label: "Pump capacity", value: "3 HP" },
      { label: "Max head", value: "80 m" },
      { label: "Daily output", value: "Up to 60,000 litres" },
      { label: "Array size", value: "3.6 kW" },
      { label: "Controller", value: "MPPT VFD with LCD" },
      { label: "Warranty", value: "2 years" },
    ],
    is_active: true,
    is_featured: false,
    created_at: baseDate,
  },
  {
    id: "prd-6",
    slug: "solar-street-light-100w",
    name: "SolarBright Street Light 100W",
    title: "All-in-one solar LED street light with motion sensing",
    description:
      "A self-contained street light that charges during the day and lights streets, yards and commercial premises all night. The integrated lithium battery holds up to three nights of autonomy, and motion sensing raises brightness only when someone is nearby.\n\nInstallation needs no trenching or wiring — mount it on a pole and it is ready to run.",
    price: 48500,
    discount_price: 42000,
    category_id: "cat-accessories",
    images: ["/images/product-street-light.jpg"],
    videos: [],
    documents: [],
    features: [
      "100W integrated LED with 18,000 lumens",
      "3 nights of backup on a full charge",
      "PIR motion sensing with dimming mode",
      "IP66 weatherproof aluminium housing",
      "No wiring or trenching required",
    ],
    specifications: [
      { label: "LED power", value: "100 W" },
      { label: "Luminous flux", value: "18,000 lm" },
      { label: "Battery", value: "LiFePO4 60 Ah" },
      { label: "Solar panel", value: "120 W monocrystalline" },
      { label: "Protection rating", value: "IP66" },
      { label: "Warranty", value: "3 years" },
    ],
    is_active: true,
    is_featured: false,
    created_at: baseDate,
  },
  {
    id: "prd-7",
    slug: "solar-water-heater-200l",
    name: "SolarHeat 200L Water Heater",
    title: "Evacuated tube geyser that delivers hot water without a gas bill",
    description:
      "SolarHeat uses vacuum-insulated glass tubes to heat water with sunlight alone, holding it in a pressurised stainless steel tank that stays warm overnight. A single 200 litre unit comfortably covers a family of five through winter mornings.\n\nThe system runs without gas or electricity, so it keeps working during load shedding and gas closures, and needs little more than an annual rinse of the tubes.",
    price: 132000,
    discount_price: 118000,
    category_id: "cat-water-heating",
    images: ["/images/product-solar-geyser.jpg"],
    videos: [],
    documents: [{ name: "Datasheet (PDF)", url: "/docs/sample-datasheet.pdf" }],
    features: [
      "200 litre pressurised stainless steel tank",
      "24 vacuum-insulated evacuated tubes",
      "No gas or electricity consumption",
      "Holds temperature overnight in winter",
      "Optional electric backup element",
    ],
    specifications: [
      { label: "Tank capacity", value: "200 litres" },
      { label: "Tubes", value: "24 × 58 mm evacuated tubes" },
      { label: "Tank material", value: "SUS 304 stainless steel" },
      { label: "Insulation", value: "55 mm polyurethane foam" },
      { label: "Working pressure", value: "6 bar" },
      { label: "Warranty", value: "7 years" },
    ],
    is_active: true,
    is_featured: false,
    created_at: baseDate,
  },
  {
    id: "prd-8",
    slug: "on-grid-inverter-5kw",
    name: "GridLink On-Grid Inverter 5kW",
    title: "Net-metering ready string inverter for homes without batteries",
    description:
      "GridLink is built for households that want to cut their bill through net metering rather than store energy. It exports surplus production straight to the grid and is certified for utility approval, so the paperwork goes through without surprises.\n\nTwo MPPT trackers and a wide start-up voltage keep the system generating from first light to dusk, and the app shows exactly how many units you have exported each day.",
    price: 210000,
    discount_price: 189000,
    category_id: "cat-inverters",
    images: ["/images/product-ongrid-inverter.jpg"],
    videos: [],
    documents: [{ name: "Installation Manual (PDF)", url: "/docs/sample-datasheet.pdf" }],
    features: [
      "5kW output certified for net metering",
      "Dual MPPT trackers with 98.2% peak efficiency",
      "Export monitoring through mobile app",
      "Fanless cooling for silent operation",
      "IP65 housing suitable for outdoor walls",
    ],
    specifications: [
      { label: "Rated power", value: "5000 W" },
      { label: "Max PV input", value: "7500 W" },
      { label: "MPPT trackers", value: "2" },
      { label: "Peak efficiency", value: "98.2%" },
      { label: "Grid type", value: "Single phase, 230 V" },
      { label: "Protection rating", value: "IP65" },
      { label: "Warranty", value: "5 years" },
    ],
    is_active: true,
    is_featured: false,
    created_at: baseDate,
  },
  {
    id: "prd-9",
    slug: "hybrid-inverter-15kw-three-phase",
    name: "PowerCore Hybrid Inverter 15kW",
    title: "Three-phase hybrid inverter for large homes and small industry",
    description:
      "The 15kW three-phase PowerCore carries heavy inductive loads — lifts, compressors, deep freezers and multi-tonne air conditioning — without tripping. Three MPPT trackers allow large arrays to be split across several roof orientations.\n\nUnits can be paralleled up to 90kW, so the same platform grows with a factory or a commercial building instead of being replaced.",
    price: 745000,
    discount_price: null,
    category_id: "cat-inverters",
    images: ["/images/product-inverter.jpg"],
    videos: [],
    documents: [],
    features: [
      "15kW three-phase output, 30kW surge",
      "Three MPPT trackers for complex roofs",
      "Parallel up to 6 units for 90kW",
      "Generator input with automatic start",
      "Remote diagnostics and firmware updates",
    ],
    specifications: [
      { label: "Rated power", value: "15,000 W" },
      { label: "Max PV input", value: "22,500 W" },
      { label: "MPPT trackers", value: "3" },
      { label: "Battery voltage", value: "192 – 600 V" },
      { label: "Grid type", value: "Three phase, 400 V" },
      { label: "Peak efficiency", value: "97.9%" },
      { label: "Warranty", value: "5 years" },
    ],
    is_active: true,
    is_featured: false,
    created_at: baseDate,
  },
  {
    id: "prd-10",
    slug: "lithium-battery-5kwh",
    name: "EnduraStore 5kWh Lithium Battery",
    title: "Compact LiFePO4 storage for essential-load backup",
    description:
      "The 5kWh EnduraStore covers the loads that matter during an outage — lights, fans, routers, a refrigerator and a couple of ceiling fans — at roughly half the footprint and cost of a full-home battery.\n\nIt stacks with additional units later, so a household can start small and expand capacity as budget allows without replacing the original battery.",
    price: 335000,
    discount_price: 312000,
    category_id: "cat-batteries",
    images: ["/images/product-battery.jpg"],
    videos: [],
    documents: [],
    features: [
      "5 kWh usable capacity, stackable to 20 kWh",
      "LiFePO4 cells rated for 6,000+ cycles",
      "Wall or floor mounting",
      "Integrated battery management system",
      "10-year warranty",
    ],
    specifications: [
      { label: "Usable capacity", value: "5 kWh" },
      { label: "Nominal voltage", value: "51.2 V" },
      { label: "Chemistry", value: "LiFePO4" },
      { label: "Cycle life", value: "6000+ cycles at 80% DoD" },
      { label: "Dimensions", value: "560 × 480 × 170 mm" },
      { label: "Weight", value: "52 kg" },
      { label: "Warranty", value: "10 years" },
    ],
    is_active: true,
    is_featured: false,
    created_at: baseDate,
  },
  {
    id: "prd-11",
    slug: "complete-home-system-5kw",
    name: "Complete Home Solar System 5kW",
    title: "Entry-level rooftop package sized for an average household",
    description:
      "A 5kW package covering a typical three-bedroom home running fans, lights, a refrigerator and one or two air conditioners. It includes panels, inverter, mounting, protection gear and installation — nothing else to buy.\n\nWe survey the roof, size the array against twelve months of your electricity bills and handle the net-metering application end to end.",
    price: 1150000,
    discount_price: 1075000,
    category_id: "cat-systems",
    images: ["/images/product-rooftop-system.jpg", "/images/product-inverter.jpg"],
    videos: [],
    documents: [{ name: "System Brochure (PDF)", url: "/docs/sample-datasheet.pdf" }],
    features: [
      "9 × 580W monocrystalline panels",
      "5kW on-grid inverter with monitoring",
      "Galvanised mounting structure and DC protection",
      "Complete installation and commissioning",
      "Net-metering documentation support",
    ],
    specifications: [
      { label: "System size", value: "5 kW" },
      { label: "Estimated output", value: "650 – 720 units per month" },
      { label: "Roof area required", value: "Approx. 300 sq ft" },
      { label: "Installation time", value: "2 – 3 working days" },
      { label: "Warranty", value: "System warranty up to 25 years" },
    ],
    is_active: true,
    is_featured: true,
    created_at: baseDate,
  },
  {
    id: "prd-12",
    slug: "mounting-structure-kit",
    name: "AlumaRail Mounting Structure Kit",
    title: "Anodised aluminium rails and clamps for rooftop arrays",
    description:
      "AlumaRail is the hardware that keeps an array on the roof through monsoon winds. The rails are anodised aluminium rather than painted steel, so they do not rust at the cut ends, and the stainless fasteners stay serviceable years later.\n\nEach kit mounts four panels and includes rails, end clamps, mid clamps and all required bolts — sized for standard 2278 × 1134 mm modules.",
    price: 26500,
    discount_price: null,
    category_id: "cat-accessories",
    images: ["/images/product-mounting-structure.jpg"],
    videos: [],
    documents: [],
    features: [
      "Mounts four standard panels per kit",
      "Anodised aluminium rails, no rusting",
      "Stainless steel nuts and bolts",
      "Rated for 150 km/h wind load",
      "Fits flat roofs, sloped roofs and ground mounts",
    ],
    specifications: [
      { label: "Rail material", value: "Anodised aluminium 6005-T5" },
      { label: "Clamp range", value: "30 – 40 mm module frames" },
      { label: "Fasteners", value: "SS 304 stainless steel" },
      { label: "Wind load", value: "Up to 150 km/h" },
      { label: "Coverage", value: "4 panels per kit" },
      { label: "Warranty", value: "10 years" },
    ],
    is_active: true,
    is_featured: false,
    created_at: baseDate,
  },
  {
    id: "prd-13",
    slug: "solar-dc-cable-kit",
    name: "SolarLink DC Cable & Connector Kit",
    title: "UV-rated 4mm² solar cable with weatherproof connectors",
    description:
      "Cheap cable is the most common cause of underperforming arrays. SolarLink uses tinned copper conductors in double-insulated, UV-stable sheathing rated for 25 years on an exposed roof, so voltage drop stays low for the life of the system.\n\nEach kit contains 50 metres of red and 50 metres of black cable with ten pairs of IP68 connectors and a crimping guide.",
    price: 18900,
    discount_price: 16500,
    category_id: "cat-accessories",
    images: ["/images/product-dc-cable-kit.jpg"],
    videos: [],
    documents: [],
    features: [
      "50 m red + 50 m black 4mm² cable",
      "Tinned copper for corrosion resistance",
      "Double insulated, UV and ozone stable",
      "10 pairs of IP68 rated connectors",
      "Rated 1500 V DC, -40°C to +90°C",
    ],
    specifications: [
      { label: "Conductor", value: "4 mm² tinned copper" },
      { label: "Cable length", value: "50 m × 2 rolls" },
      { label: "Voltage rating", value: "1500 V DC" },
      { label: "Connectors", value: "10 pairs, IP68" },
      { label: "Temperature range", value: "-40°C to +90°C" },
      { label: "Service life", value: "25 years outdoors" },
    ],
    is_active: true,
    is_featured: false,
    created_at: baseDate,
  },
];

export const seedAnnouncements: Announcement[] = [
  {
    id: "ann-1",
    title: "New Solar Scheme Available",
    message:
      "Get up to 12% off complete home solar systems this month, with flexible instalment plans and free site survey across all major cities.",
    cta_label: "View offers",
    cta_href: "/products",
    is_active: true,
    created_at: baseDate,
  },
];
