import type { Announcement, Category, Product } from "./types";

/**
 * Demo content used when Supabase environment variables are not configured yet,
 * so the site is fully browsable before the database is connected.
 */
export const seedCategories: Category[] = [
  { id: "cat-panels", name: "Solar Panels", slug: "solar-panels" },
  { id: "cat-inverters", name: "Inverters", slug: "inverters" },
  { id: "cat-batteries", name: "Batteries", slug: "batteries" },
  { id: "cat-systems", name: "Complete Systems", slug: "complete-systems" },
  { id: "cat-accessories", name: "Accessories", slug: "accessories" },
];

const baseDate = "2025-01-15T10:00:00.000Z";

export const seedProducts: Product[] = [
  {
    id: "prd-1",
    slug: "monocrystalline-solar-panel-580w",
    name: "SunPower Mono 580W Panel",
    title: "High-efficiency monocrystalline module for rooftop and commercial arrays",
    description:
      "Our flagship 580W monocrystalline module delivers dependable output even in high ambient temperatures. Half-cut cell architecture reduces resistive loss and keeps the panel producing when part of the array is shaded, while the anodised aluminium frame is tested for heavy wind and snow loads.\n\nEvery module is individually flash-tested before dispatch and shipped with a 25-year linear performance warranty, making it a safe long-term investment for homes, factories and agricultural sites.",
    price: 34500,
    discount_price: 29900,
    category_id: "cat-panels",
    images: ["/images/product-solar-panel.jpg", "/images/product-rooftop-system.jpg"],
    videos: [],
    documents: [{ name: "Datasheet (PDF)", url: "/docs/sample-datasheet.pdf" }],
    features: [
      "580W peak output with 22.4% module efficiency",
      "Half-cut mono PERC cells for better shade tolerance",
      "Anti-reflective, self-cleaning tempered glass",
      "Corrosion-resistant anodised aluminium frame",
      "25-year linear performance warranty",
    ],
    specifications: [
      { label: "Peak power", value: "580 W" },
      { label: "Module efficiency", value: "22.4%" },
      { label: "Cell type", value: "Monocrystalline PERC, half-cut" },
      { label: "Dimensions", value: "2278 × 1134 × 35 mm" },
      { label: "Weight", value: "27.5 kg" },
      { label: "Operating temperature", value: "-40°C to +85°C" },
      { label: "Warranty", value: "12 years product / 25 years performance" },
    ],
    is_active: true,
    is_featured: true,
    created_at: baseDate,
  },
  {
    id: "prd-2",
    slug: "hybrid-inverter-8kw",
    name: "PowerCore Hybrid Inverter 8kW",
    title: "Grid-tied hybrid inverter with battery backup and app monitoring",
    description:
      "The PowerCore 8kW hybrid inverter runs your home on solar during the day, charges the battery with surplus energy and switches to backup in under 10 milliseconds when the grid drops. Dual MPPT trackers let you split panels across two roof faces without losing yield.\n\nA colour display and mobile app give you live production, consumption and battery data, so you always know exactly where your energy is going.",
    price: 415000,
    discount_price: null,
    category_id: "cat-inverters",
    images: ["/images/product-inverter.jpg"],
    videos: [],
    documents: [{ name: "Installation Manual (PDF)", url: "/docs/sample-datasheet.pdf" }],
    features: [
      "8kW continuous output, 16kW surge for motor loads",
      "Dual MPPT trackers with wide voltage window",
      "Under 10 ms transfer to backup power",
      "Wi-Fi monitoring through mobile app",
      "Works with lithium and lead-acid batteries",
    ],
    specifications: [
      { label: "Rated power", value: "8000 W" },
      { label: "Max PV input", value: "12000 W" },
      { label: "MPPT trackers", value: "2" },
      { label: "Battery voltage", value: "48 V" },
      { label: "Peak efficiency", value: "97.6%" },
      { label: "Protection rating", value: "IP65" },
      { label: "Warranty", value: "5 years" },
    ],
    is_active: true,
    is_featured: true,
    created_at: baseDate,
  },
  {
    id: "prd-3",
    slug: "lithium-battery-10kwh",
    name: "EnduraStore 10kWh Lithium Battery",
    title: "Wall-mounted LiFePO4 storage for reliable overnight backup",
    description:
      "EnduraStore stores the solar energy you generate during the day so your home keeps running through load shedding and after sunset. The LiFePO4 chemistry is rated for 6,000+ cycles, which means a decade of daily use without meaningful capacity loss.\n\nAn integrated battery management system continuously balances cells and protects against over-charge, over-discharge and thermal events.",
    price: 620000,
    discount_price: 575000,
    category_id: "cat-batteries",
    images: ["/images/product-battery.jpg"],
    videos: [],
    documents: [],
    features: [
      "10 kWh usable capacity, stackable to 40 kWh",
      "LiFePO4 cells rated for 6,000+ cycles",
      "Built-in smart battery management system",
      "Slim wall-mounted design with LED status",
      "10-year warranty",
    ],
    specifications: [
      { label: "Usable capacity", value: "10 kWh" },
      { label: "Nominal voltage", value: "51.2 V" },
      { label: "Chemistry", value: "LiFePO4" },
      { label: "Cycle life", value: "6000+ cycles at 80% DoD" },
      { label: "Dimensions", value: "700 × 550 × 190 mm" },
      { label: "Weight", value: "96 kg" },
      { label: "Warranty", value: "10 years" },
    ],
    is_active: true,
    is_featured: true,
    created_at: baseDate,
  },
  {
    id: "prd-4",
    slug: "complete-home-system-10kw",
    name: "Complete Home Solar System 10kW",
    title: "Turnkey rooftop package including panels, inverter, mounting and installation",
    description:
      "A fully engineered 10kW package for medium to large homes, covering everything from site survey and structural mounting to net-metering paperwork. We size the array around your actual consumption so you are not paying for capacity you will never use.\n\nInstallation is completed by our own certified crews, and the system is handed over with commissioning reports and a full performance walkthrough.",
    price: 2450000,
    discount_price: 2295000,
    category_id: "cat-systems",
    images: ["/images/product-rooftop-system.jpg", "/images/product-solar-panel.jpg"],
    videos: [],
    documents: [{ name: "System Brochure (PDF)", url: "/docs/sample-datasheet.pdf" }],
    features: [
      "18 × 580W monocrystalline panels",
      "10kW hybrid inverter with monitoring",
      "Galvanised mounting structure and DC protection",
      "Complete installation and commissioning",
      "Net-metering documentation support",
    ],
    specifications: [
      { label: "System size", value: "10 kW" },
      { label: "Estimated output", value: "1,300 – 1,450 units per month" },
      { label: "Roof area required", value: "Approx. 600 sq ft" },
      { label: "Installation time", value: "3 – 5 working days" },
      { label: "Warranty", value: "System warranty up to 25 years" },
    ],
    is_active: true,
    is_featured: true,
    created_at: baseDate,
  },
  {
    id: "prd-5",
    slug: "solar-water-pump-system",
    name: "AgriFlow Solar Water Pump",
    title: "Diesel-free irrigation powered entirely by sunlight",
    description:
      "AgriFlow replaces diesel pumping with a solar-driven submersible system built for daily agricultural use. The VFD controller adjusts pump speed with available sunlight, delivering steady flow from early morning to late afternoon.\n\nWith no fuel bills and almost no maintenance, most growers recover the cost of the system within a few seasons.",
    price: 385000,
    discount_price: null,
    category_id: "cat-systems",
    images: ["/images/product-solar-pump.jpg"],
    videos: [],
    documents: [],
    features: [
      "Runs without diesel, grid power or batteries",
      "Variable frequency drive matches pump speed to sunlight",
      "Stainless steel submersible pump body",
      "Dry-run and over-voltage protection",
      "Suitable for 1 – 5 HP irrigation needs",
    ],
    specifications: [
      { label: "Pump capacity", value: "3 HP" },
      { label: "Max head", value: "80 m" },
      { label: "Daily output", value: "Up to 60,000 litres" },
      { label: "Array size", value: "3.6 kW" },
      { label: "Controller", value: "MPPT VFD with LCD" },
      { label: "Warranty", value: "2 years" },
    ],
    is_active: true,
    is_featured: false,
    created_at: baseDate,
  },
  {
    id: "prd-6",
    slug: "solar-street-light-100w",
    name: "SolarBright Street Light 100W",
    title: "All-in-one solar LED street light with motion sensing",
    description:
      "A self-contained street light that charges during the day and lights streets, yards and commercial premises all night. The integrated lithium battery holds up to three nights of autonomy, and motion sensing raises brightness only when someone is nearby.\n\nInstallation needs no trenching or wiring — mount it on a pole and it is ready to run.",
    price: 48500,
    discount_price: 42000,
    category_id: "cat-accessories",
    images: ["/images/product-street-light.jpg"],
    videos: [],
    documents: [],
    features: [
      "100W integrated LED with 18,000 lumens",
      "3 nights of backup on a full charge",
      "PIR motion sensing with dimming mode",
      "IP66 weatherproof aluminium housing",
      "No wiring or trenching required",
    ],
    specifications: [
      { label: "LED power", value: "100 W" },
      { label: "Luminous flux", value: "18,000 lm" },
      { label: "Battery", value: "LiFePO4 60 Ah" },
      { label: "Solar panel", value: "120 W monocrystalline" },
      { label: "Protection rating", value: "IP66" },
      { label: "Warranty", value: "3 years" },
    ],
    is_active: true,
    is_featured: false,
    created_at: baseDate,
  },
];

export const seedAnnouncements: Announcement[] = [
  {
    id: "ann-1",
    title: "New Solar Scheme Available",
    message:
      "Get up to 12% off complete home solar systems this month, with flexible instalment plans and free site survey across all major cities.",
    cta_label: "View offers",
    cta_href: "/products",
    is_active: true,
    created_at: baseDate,
  },
];
